name: Ejecutar script de Python

on:
  pull_request:
    branches: [ Master ]
    types: [ closed ]

jobs:
  run-python-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ejecutar script
        run: python git_practica.py
